on:
  push:
    tags:
      - "v*" # Push version tags

name: Upload Release

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Zip maps
        run: |
          mkdir -p ./dist
          zip ./dist/flat.zip ./maps/flat && zip ./dist/template.zip ./maps/template
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Mod File
        id: upload-mod-file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/custommaploader.js
          asset_name: custommaploader.js
          asset_content_type: text/javascript
      - name: Upload Example Map
        id: upload-example-map
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/flat.zip
          asset_name: flat.zip
          asset_content_type: application/zip
      - name: Upload Map Template
        id: upload-map-template
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/template.zip
          asset_name: template.zip
          asset_content_type: application/zip
